name: anote
description: "Your AI Second Brain."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: any
  go_router: any
  google_fonts: any
  cupertino_icons: any
  flutter_animate: any
  shared_preferences: any
  path_provider: any
  path: any
  uuid: any
  intl: any
  equatable: any
  image_picker: ^1.1.2
  record: ^5.0.5
  audioplayers: ^6.1.0
  speech_to_text: ^6.6.1
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
