name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          cache: true

      - name: Generate Android Project
        run: |
          flutter create --org com.asilbek.anote --project-name anote .
          
      - name: Patch Gradle and Manifest
        run: |
          sed -i 's/ext.kotlin_version = .*/ext.kotlin_version = "1.9.22"/g' android/build.gradle
          sed -i 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 34/g' android/app/build.gradle
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 24/g' android/app/build.gradle
          sed -i 's/android:label="anote"/android:label="ANOTE"/g' android/app/src/main/AndroidManifest.xml
          sed -i '/<application/i \    <uses-permission android:name="android.permission.CAMERA" />\n    <uses-permission android:name="android.permission.RECORD_AUDIO" />\n    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />' android/app/src/main/AndroidManifest.xml

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate App Icons
        run: flutter pub run flutter_launcher_icons

      - name: Build APK
        run: |
          flutter build apk --release
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/ANOTE-latest.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: anote-release-apk
          path: build/app/outputs/flutter-apk/ANOTE-latest.apk
